spring.application.name=order-tracker

spring.datasource.url=jdbc:sqlite:./data/app.db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false

spring.data.web.pageable.max-page-size=100
